#!/bin/sh

set -e

# Install and use node LTS
echo "installing node (via nvm)..."
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

# Source nvm
NVM_DIR="$HOME/.nvm"
source "$NVM_DIR/nvm.sh"

# Install and use node version 10 by default
nvm install --lts
nvm alias default lts

echo "Installing yarn..."
# Install yarn
curl -o- -L https://yarnpkg.com/install.sh | bash

echo "Installing global packages..."
# Install a few packages globally
yarn global add serve fkill-cli npm-quick-run semantic-release-cli \
npm-check-updates prettier eslint create-react-app
