#!/bin/sh

set -e

# Install node
echo "installing node (via n-install)"
curl -L https://git.io/n-install | bash

# Install and use node LTS
curl -sL https://git.io/n-install | bash -s -- -q

# Install yarn
curl -o- -L https://yarnpkg.com/install.sh | bash

# Install a few packages globally
yarn global add serve fkill-cli npm-quick-run semantic-release-cli \
npm-check-updates prettier create-react-app
