#!/bin/sh

set -e

source setup-helpers

# NOTE: We're skipping installation part
# as it'll be installed along with homebrew
# brew install git

install_dotfile "gitignore"

git config --global alias.br branch
git config --global alias.cm commit
git config --global alias.cmm "commit -m"
git config --global alias.co checkout
git config --global alias.lol "log --graph --decorate --pretty=oneline --abbrev-commit"
git config --global alias.lola "log --graph --decorate --pretty=oneline --abbrev-commit --all"
git config --global alias.ls ls-files
git config --global alias.st status

git config --global color.ui true

git config --global core.autocrlf input
git config --global core.editor vim
git config --global core.eol lf
git config --global core.excludesfile "$HOME/.gitignore"

git config --global credential.helper osxkeychain

git config --global push.default current

git config --global url.https://.insteadOf git://

git config --global user.email "iamfotx@gmail.com"
git config --global user.name "iamfotx"

echo "Generating a new SSH key for GitHub"
ssh-keygen -q -t ed25519 -N '' -C "iamfotx@gmail.com" -f ~/.ssh/id_ed25519 <<<y >/dev/null 2>&1
eval "$(ssh-agent -s)"
touch ~/.ssh/config
echo "Host *\n AddKeysToAgent yes\n UseKeychain yes\n IdentityFile ~/.ssh/id_ed25519" | tee ~/.ssh/config
ssh-add -K ~/.ssh/id_ed25519
echo "run 'pbcopy < ~/.ssh/id_ed25519.pub' and paste that into GitHub"