#!/bin/sh

set -e

echo "Hello $(whoami)! Let's get you set up for Monday."

uname=`uname`
platform="unknown"
if [[ $uname == "Darwin" ]]; then
   platform="macos"
elif [[ $uname == "Linux" ]]; then
   platform="linux"
fi

if [ "$platform" == "macos" ]; then
  ./setup-homebrew --install-apps
  ./setup-mac
fi

./setup-zsh
./setup-git
./setup-node
./setup-vim